[build-system]
requires = ["setuptools>=40.8.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.black]
force-exclude = '''
  exspy/misc/eds/ffast_mac.py
  | exspy/misc/elements.py
'''

[tool.pytest.ini_options]
addopts = "-ra -n auto --dist loadfile"
testpaths = ["hyperspy/tests", ]
