name: Docs

on: [push, pull_request]

jobs:
  build_doc_PR:
    # This build is to automatically add comments on PR
    name: PR comments
    runs-on: ubuntu-latest
    env:
      BUILD_DEPS: python3-dev build-essential graphviz
      LATEX_DEPS: dvipng latexmk texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended

    steps:
      - uses: actions/checkout@v4

      - uses: ericpre/sphinx-action@latest_sphinx
        with:
          pre-build-command: "apt-get update -y && apt-get install -y ${{ env.BUILD_DEPS }} ${{ env.LATEX_DEPS }} && pip install .'[doc]'"
          build-command: make html
          docs-folder: doc/

      - uses: actions/upload-artifact@v3
        with:
          path: ./doc/_build/html/
          name: docs_build

  build_docs:
    # This build is to check links and update table of supported formats
    name: Check links
    runs-on: ubuntu-latest
    env:
      DOCS_PATH: ./doc/_build/html/
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v4
        name: Install Python
        with:
          python-version: '3.11'

      - name: Install build docs
        shell: bash -l {0}
        run: |
          pip install .'[doc]'

      - name: Check links
        shell: bash -l {0}
        run: |
          cd doc
          make linkcheck

      - name: Build docs
        shell: bash -l {0}
        run: |
          cd doc
          make SPHINXOPTS="-W --keep-going" html

      - uses: actions/upload-artifact@v3
        with:
          path: ${{ env.DOCS_PATH }}
          name: docs_html

  push_docs:
    # This build is to push changes to gh-pages branch (https://hyperspy.org/exspy)
    needs: build_docs
    name: Push to gh-pages
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' && github.repository == 'hyperspy/exspy' }}
    permissions:
      # needs write permission to push the docs to gh-pages
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: gh-pages

      - uses: actions/download-artifact@v3
        with:
          name: docs_html
          path: .

      - name: list files
        run: |
          ls

      - name: Git status
        run: |
          git status
          git status -s
          if [[ $(git status -s) ]]; then
            HAS_CHANGES='true'
          else
            HAS_CHANGES='false'
          fi
          echo "HAS_CHANGES=${HAS_CHANGES}" >> $GITHUB_ENV

      - name: Commit files
        # Skip when there is nothing to commit
        if: ${{ env.HAS_CHANGES == 'true' }}
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add -A
          git commit -m "Update docs build" -a

      - name: Push changes
        if: ${{ env.HAS_CHANGES == 'true' }}
        uses: ad-m/github-push-action@d91a481090679876dfc4178fef17f286781251df
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
